### ISSUE TITLE
Run Miri tests with strict provenance

### ISSUE THREAD

**Issue by lopopolo** [artichoke/intaglio#156]
See:

- https://github.com/rust-lang/miri/pull/2045

The current hard mode is:

```console
$ MIRIFLAGS="-Zmiri-strict-provenance -Zmiri-check-number-validity -Zmiri-symbolic-alignment-check -Zrandomize-layout" cargo +nightly miri test --test leak_drop
```

Blockers:

- https://github.com/rust-lang/rust/issues/96163

**Comment by CAD97** [comment]
(`-Zmiri-strict-provenance` implies `-Zmiri-check-number-validity` now.)

In the meantime, you can use `--target` to avoid testing the macOS target. (Miri, as an interpreter VM, can test any target on any host.)

**Comment by lopopolo** [comment]
Thanks for fixing this on macOS with https://github.com/rust-lang/rust/pull/96167 @CAD97. The tests pass locally on my Mac for me now with `rustc 1.62.0-nightly (f4ec0e7cf 2022-04-22)`.

PR to enable this is:

- https://github.com/artichoke/intaglio/pull/157
